version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: chainlink_event_store_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - backend
  redis:
    image: redis:7
    container_name: event_tracker_cache
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  pgdata:
  redisdata:
